apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: titlecreator
spec:
  template:
    spec:
      containers:
        - image: us-west2-docker.pkg.dev/title-gen/titlegenerator/titlecreator:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080" 